# Generated by Django 4.2.3 on 2023-07-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(blank=True, max_length=800)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('attachment_file', models.FileField(upload_to='')),
            ],
        ),
    ]
